version: '3'

services:
  backend:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    volumes:
      - .:/code
    env_file:
      - .env

  job_updater:
    build: .
    command: python app/update_jobs.py
    volumes:
      - .:/code
    env_file:
      - .env
