"""Add desired fields to user profile

Revision ID: 3d723ba7e91d
Revises: 603da9b28c5c
Create Date: 2025-06-17 15:37:55.272410

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d723ba7e91d'
down_revision: Union[str, None] = '603da9b28c5c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profiles', sa.Column('desired_city', sa.String(), nullable=True))
    op.add_column('user_profiles', sa.Column('desired_format', sa.String(), nullable=True))
    op.add_column('user_profiles', sa.Column('desired_work_time', sa.String(), nullable=True))
    op.drop_column('user_profiles', 'desired_salary')
    op.add_column('user_profiles', sa.Column('desired_salary', sa.Integer(), nullable=True))


    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_profiles', 'desired_salary',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_column('user_profiles', 'desired_work_time')
    op.drop_column('user_profiles', 'desired_format')
    op.drop_column('user_profiles', 'desired_city')
    # ### end Alembic commands ###
