"""add user telegram channel model

Revision ID: 466d2b2b9c52
Revises: 0f43d6fd9c7e
Create Date: 2025-06-25 09:01:20.047623

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '466d2b2b9c52'
down_revision: Union[str, None] = '0f43d6fd9c7e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_telegram_channels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('channel_username', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'channel_username', name='uq_user_channel')
    )
    op.create_index(op.f('ix_user_telegram_channels_id'), 'user_telegram_channels', ['id'], unique=False)
    op.add_column('job_posts', sa.Column('contact_info', sa.String(), nullable=True))
    op.add_column('job_posts', sa.Column('telegram_message_id', sa.Integer(), nullable=False))
    op.add_column('job_posts', sa.Column('channel_username', sa.String(), nullable=False))
    op.add_column('job_posts', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('job_posts', sa.Column('parsed_at', sa.DateTime(), nullable=True))
    op.create_unique_constraint('uq_telegram_message', 'job_posts', ['telegram_message_id', 'channel_username'])
    op.drop_column('job_posts', 'link')
    op.drop_column('job_posts', 'published_at')
    op.drop_column('job_posts', 'source')
    op.alter_column('user_profiles', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_profiles', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('job_posts', sa.Column('source', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('job_posts', sa.Column('published_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('job_posts', sa.Column('link', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint('uq_telegram_message', 'job_posts', type_='unique')
    op.drop_column('job_posts', 'parsed_at')
    op.drop_column('job_posts', 'created_at')
    op.drop_column('job_posts', 'channel_username')
    op.drop_column('job_posts', 'telegram_message_id')
    op.drop_column('job_posts', 'contact_info')
    op.drop_index(op.f('ix_user_telegram_channels_id'), table_name='user_telegram_channels')
    op.drop_table('user_telegram_channels')
    # ### end Alembic commands ###
