"""make telegram_id nullable

Revision ID: a5a4fb4a83ea
Revises: 1ac40d598d4f
Create Date: 2025-06-23 09:22:13.953332

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a5a4fb4a83ea'
down_revision: Union[str, None] = '1ac40d598d4f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_profiles', 'telegram_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_profiles', 'telegram_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
