"""add user telegram channel model

Revision ID: b1ad45b0ac56
Revises: 8c30109cd318
Create Date: 2025-06-25 10:17:18.073330

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b1ad45b0ac56'
down_revision: Union[str, None] = '8c30109cd318'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_posts', sa.Column('format', sa.String(), nullable=True))
    op.add_column('job_posts', sa.Column('channel_name', sa.String(), nullable=True))
    op.alter_column('job_posts', 'telegram_message_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(op.f('uq_telegram_message'), 'job_posts', type_='unique')
    op.drop_column('job_posts', 'work_format')
    op.drop_column('job_posts', 'channel_username')
    op.alter_column('user_profiles', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_index(op.f('ix_user_telegram_channels_id'), 'user_telegram_channels', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_telegram_channels_id'), table_name='user_telegram_channels')
    op.alter_column('user_profiles', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.add_column('job_posts', sa.Column('channel_username', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('job_posts', sa.Column('work_format', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_unique_constraint(op.f('uq_telegram_message'), 'job_posts', ['telegram_message_id', 'channel_username'], postgresql_nulls_not_distinct=False)
    op.alter_column('job_posts', 'telegram_message_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('job_posts', 'channel_name')
    op.drop_column('job_posts', 'format')
    # ### end Alembic commands ###
