"""your message

Revision ID: b3c3df3cdee5
Revises: b9888cacaae0
Create Date: 2025-06-24 12:04:12.971787

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b3c3df3cdee5'
down_revision: Union[str, None] = 'b9888cacaae0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('user_profiles_user_id_key'), 'user_profiles', type_='unique')
    op.drop_constraint(op.f('user_profiles_user_id_fkey'), 'user_profiles', type_='foreignkey')
    op.drop_column('user_profiles', 'user_id')
    op.add_column('users', sa.Column('user_profile_id', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'users', ['user_profile_id'])
    op.create_foreign_key(None, 'users', 'user_profiles', ['user_profile_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'user_profile_id')
    op.add_column('user_profiles', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('user_profiles_user_id_fkey'), 'user_profiles', 'users', ['user_id'], ['id'])
    op.create_unique_constraint(op.f('user_profiles_user_id_key'), 'user_profiles', ['user_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
