"""Add UserTelegramChannel model and update JobPost model

Revision ID: 8c30109cd318
Revises: 2283043b5078
Create Date: 2025-06-25 10:20:13.931405

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8c30109cd318'
down_revision: Union[str, None] = '2283043b5078'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table('user_telegram_channels',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('channel_username', sa.String(), nullable=False),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    # Comment out these lines if the columns already exist:
    # op.add_column('job_posts', sa.Column('contact_info', sa.String(), nullable=True))
    # op.add_column('job_posts', sa.Column('created_at', sa.DateTime(), nullable=True))
    # op.add_column('job_posts', sa.Column('format', sa.String(), nullable=True))
    # op.add_column('job_posts', sa.Column('parsed_at', sa.DateTime(), nullable=True))
    # op.add_column('job_posts', sa.Column('channel_name', sa.String(), nullable=True))

    # Avoid dropping existing fields unless you're sure
    # op.drop_column('job_posts', 'link')
    # op.drop_column('job_posts', 'source')
    # op.drop_column('job_posts', 'published_at')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_posts', sa.Column('published_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('job_posts', sa.Column('source', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('job_posts', sa.Column('link', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('job_posts', 'channel_name')
    op.drop_column('job_posts', 'parsed_at')
    op.drop_column('job_posts', 'format')
    op.drop_column('job_posts', 'created_at')
    op.drop_column('job_posts', 'contact_info')
    op.drop_table('user_telegram_channels')
    # ### end Alembic commands ###
