"""Updated UserProfile and JobPost models

Revision ID: e79efd3410f3
Revises: 3d723ba7e91d
Create Date: 2025-06-18 09:41:14.461619

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e79efd3410f3'
down_revision: Union[str, None] = '3d723ba7e91d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_posts', sa.Column('salary', sa.Integer(), nullable=True))
    op.add_column('job_posts', sa.Column('location', sa.String(), nullable=True))
    op.add_column('job_posts', sa.Column('deadline', sa.DateTime(), nullable=True))
    op.add_column('user_profiles', sa.Column('gender', sa.String(), nullable=True))
    op.add_column('user_profiles', sa.Column('phone_number', sa.String(), nullable=True))
    op.add_column('user_profiles', sa.Column('email', sa.String(), nullable=True))
    op.add_column('user_profiles', sa.Column('citizenship', sa.String(), nullable=True))
    op.add_column('user_profiles', sa.Column('address', sa.String(), nullable=True))
    op.add_column('user_profiles', sa.Column('education', sa.String(), nullable=True))
    op.add_column('user_profiles', sa.Column('experience', sa.String(), nullable=True))
    op.add_column('user_profiles', sa.Column('languages', sa.String(), nullable=True))
    op.add_column('user_profiles', sa.Column('interests', sa.String(), nullable=True))
    op.add_column('user_profiles', sa.Column('achievements', sa.String(), nullable=True))
    op.add_column('user_profiles', sa.Column('industries', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profiles', 'industries')
    op.drop_column('user_profiles', 'achievements')
    op.drop_column('user_profiles', 'interests')
    op.drop_column('user_profiles', 'languages')
    op.drop_column('user_profiles', 'experience')
    op.drop_column('user_profiles', 'education')
    op.drop_column('user_profiles', 'address')
    op.drop_column('user_profiles', 'citizenship')
    op.drop_column('user_profiles', 'email')
    op.drop_column('user_profiles', 'phone_number')
    op.drop_column('user_profiles', 'gender')
    op.drop_column('job_posts', 'deadline')
    op.drop_column('job_posts', 'location')
    op.drop_column('job_posts', 'salary')
    # ### end Alembic commands ###
